repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format (Local)
        entry: clang-format -i
        language: system
        files: ^(hal|inc|src|test)/.*\.(c|h|cpp|hpp)$